/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 keyboard.gltf --transform
Author: M.Reslan (https://sketchfab.com/mreslan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-aesthetic-44bb12d306864e2cb4256a61d4168942
Title: Mechanical Keyboard - Aesthetic
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/keyboard-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Object_2.geometry}
					material={materials.Big_Buttons}
				/>
				<mesh geometry={nodes.Object_3.geometry} material={materials.Chassis} />
				<mesh
					geometry={nodes.Object_4.geometry}
					material={materials.Small_Buttons}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/keyboard-transformed.glb");
